### ISSUE TITLE
Nativescript 7 Support

### ISSUE THREAD

**Issue by fishr01** [GeoTecINIT/nativescript-task-dispatcher#18]
I am trying to get this working in NS 7, but getting the "Can't resolve 'tns-core-modules'" issue.

**Comment by agonper** [comment]
Hello @fishr01,

I'm sorry to inform that our plugin currently only supports NS 6, given none of our internal applications hadn't been migrated to NS 7. We'll do the transition as soon as this version becomes more stable.

Our main problem is that the unit test runner is not behaving properly. It is a risk to migrate such a complex plugin without being able to run the tests to double-check that everything is working as expected.

We have issues opened in the main Nativescript repo highlighting these problems. Once, they become solved we'll do the migration and release a new version.

I'll keep this issue opened to keep you updated about any changes regarding to this.

Thanks for your interest in our work. We appreciate that.

**Comment by infnetdanpro** [comment]
Same problem: 
```bash
ERROR in ../node_modules/nativescript-task-dispatcher/internal/utils/time.js
Module not found: Error: Can't resolve 'tns-core-modules/application/application'
```

**Comment by agonper** [comment]
Hi @infnetdanpro, thanks for expressing your interest in this plugin. We are aware that some of you are already using NS7, thus an update is in our track. However, we cannot provide an ETA yet given all our apps are still using NS6 due NS7 not being totally stable for our needs yet. We'll keep you updated via this thread. Thanks

**Comment by infnetdanpro** [comment]
> Hi @infnetdanpro, thanks for expressing your interest in this plugin. We are aware that some of you are already using NS7, thus an update is in our track. However, we cannot provide an ETA yet given all our apps are still using NS6 due NS7 not being totally stable for our needs yet. We'll keep you updated via this thread. Thanks

I'm using latest NS7. I deleted module and create background service independently using documentation of NS and Android

**Comment by agonper** [comment]
> I'm using latest NS7. I deleted module and create background service independently using documentation of NS and Android
Glad you could get a solution in the meantime. Kind regards

**Comment by mm-psymbl** [comment]
@agonper First of thanks for this. It's incredible how well documented and comprehensive this is. I am also in the same boat, where NS7 also lost the ability to use workers (sigh 😔 ) and now NS8 was just released :O I wonder why so many often and break changes releases actually... :/

**Comment by agonper** [comment]
Hi @mm-psymbl. Many thanks for your kind words and for your recognition towards our efforts into turning this into a high quality plugin, we appreciate them. I've been in contact with the NativeScript team and they have explained me the current situation. They are working hard in order to solve many framework internal issues, which remained unattended for a while. Next releases will be way smoother for what they've explained to me. In our case we're stuck in NS6 with completely unusable bugs with bottom navigation and the test runner. The first one affects our NativeScript apps and the second affects both apps and plugins (like this one). This plugin is quite complex and we cannot do a migration in the wild without checking if we have broken something or not. It is also heavily tested internally during weeks with ad-hoc apps made for that purpose. For now, we should be patient, they are working hard and fixing things as fast as possible given their team size and for now, CLI 6.8.0 in combination with tns-core-modules v6.5.24 have worked fine for us when creating new applications which needed a stable version.

The NS team has committed to fix those problems in the next two weeks, aligned with the release of NS8.1. By then, if everything becomes stable again. We will release the V2 of this plugin for NS7 and the V3 for NS8 (if needed). Thanks for your patience.

Regarding the use of workers. This plugin executes the code in background while the app is not visible, but it does so in the main thread, you will still need workers to perform resource intensive tasks, as stated in the README file. To my knowledge, workers are still operational (I saw a question about it in the slack community channel last week). Perhaps it has something to do with the webpack config file. I advise you to, if you have not done it yet, to join the community Slack or Discord channels (this later one is going to be the de facto communications channel starting from next year) and post your issue regarding to workers there, since they should work in NS7 and NS8.

In regards to the NS7 support, we will keep all of you up-to-date via this issue. We can assure is in our radar. Again, thanks.

**Comment by agonper** [comment]
Hi, we've just updated our internal apps to NS7, because of so we've just released the v2 of this plugin for you to take advantage of it too 😉. Theoretically it should be compatible with NS8 too, but if that's not the case, please open an issue and we'll try to support it as soon as possible.

So to sum up `npm i nativescript-task-dispatcher@2` and that's it! There are no breaking changes in the API 😃. Enjoy!
